/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ045VThwWnVNNlQza25wczhzQVVJclNWUkdRN0VCcTN4Y1U2bFNXbkFFaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0pJS21LcXFuT2VZc0FONTlIQmxHMnhDSjRSR3BIbTlSWjVBMi9zYlpRND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRRDE4RHZnQVRaV2ljeEN5WTRuZnNnRHpFa25mOGZ0T29QckNZUFJVQjBJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqL0x2TkpYVkJRUlNGMnQ5YmhsSHBLUHdOYkw0WTlaV2xMVXRieXFmcGtFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZJUjgvamZGK0FhL1BIZDQ2SFRJY0dOQVREaWpPUVJyS0ltTmNVQkRRWEE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InJBeTJrSGw2NDl3SzUyZkpIZDhzejZvZEVMMzFHdWFrT3R1YjRSL2JMazg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRVAvY25KZnFVWEFYbTZheFVvUkN4L2h2QTI1R2VZZDFTMXp2OHJRZlcwcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSzdPYWZqMGhBczQyYzVLUGp0K0U0cnE0VFdSUlEycndYeU1RMlVGQUt5ND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImloQ252THVRRU5iYkxDYWROVjluYUVsbERtQWg4S2RUUStXbzJiVGFjWU9RbGk5Z2ZBSzBUTEhhMll0N3lsVEUvVEVWblRlS3NZMmdTRDFzRTQvOURBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQzLCJhZHZTZWNyZXRLZXkiOiJFc2FmRjRvU1gwaWdEbDVlcmZibnNWUitoRTB6a0o2MVYza0h0TGlENk9BPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJoemt1Z2lsU1JHdXIxWFo4VS1OMFNRIiwicGhvbmVJZCI6ImRkYWRlNTNjLWExYzktNDI4YS05MTU2LWM4ZGE2OGI0YzRlMyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRZFh6b2Q2cTd4NkdlWFJRM2YwUFM1aUczSWc9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaVlVVFJCaHdmOUZUNlIwMFZMbCt4dDlBVmR3PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjgyQVRISjg1IiwibWUiOnsiaWQiOiIyMzQ4MDMyMTgwNzQ0OjgzQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkBBWUQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xMRjhkOEJFTFBEcHJvR0dCVWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ik5hOUpOT3FOY3B6Z05DWFVXQjZOb1hIRzJVK1R4OWtCeUU3M1VKRWROV0U9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImxiS1ZsQk9yb1FyYWxuaVBYTU9Tc1JPaHlpbFNuZ0t0K1ZhMGMyNGxXeFk2dVFUMlh6c05jclI1ZWdaRThENzU5dXFzV0JPTlFkc0Q4ZmlJaWZBMURnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJKVWphTkFOYlVkNVRlVlY2V3p2Q3pvN05Yd0hwUjUxRThCUUpZNmtkRkdKblp3ejQxNG50NWxvVHJFS1BPYk1zNWZ4dXgyQUNvU0hQcGdmZ2ZnYVFDZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgwMzIxODA3NDQ6ODNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVFd2U1RUcWpYS2M0RFFsMUZnZWphRnh4dGxQazhmWkFjaE85MUNSSFRWaCJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjg3ODc4MywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFFSXkifQ==';

const prefix = process.env.PREFIX || ',';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
